version: '3'
services:
  app:
    build: .
    container_name: hostie
    restart: always
    network_mode: host
    volumes:
      - "./config.json:/usr/src/app/config.json:ro"
      - "./provisionerPassword.txt:/usr/src/app/provisionerPassword.txt:ro"
      - "./database:/usr/src/app/database"